.github/workflows/release-openai.yml
Fix a typo in the attestation and pass an explicit path to pypa/gh-action-pypi-publish that otherwise is not finding the path.
See https://github.com/elastic/elastic-otel-python-instrumentations/actions/runs/11029392749/job/30631725343
=> ci: fix package release

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/TestChatCompletions.test_all_the_client_options.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py
Fix some precedence bugs when settings optional client attributes, before the fixes all the values had `true` as value.
=> elastic-opentelemetry-instrumentation-openai: fix tracing of openai client optional params

instrumentation/elastic-opentelemetry-instrumentation-openai/dev-requirements.txt, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py
Adapt tests to work with faster error handling from versions newer than 1.46.0 that are near a second faster for a particular test case.
=> elastic-opentelemetry-instrumentation-openai: test with latest openai

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py
Enum attributes are not strings and opentelemetry-instrument json serializer is failing to serialize them.
Reproducible with:
opentelemetry-instrument --metrics_exporter=console --traces_exporter=none examples/use_openai.py
=> elastic-opentelemetry-instrumentation-openai: schema versions are strings

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py
Fix a race condition between openai initialization and httpx instrumentation kicking in by loading the openai module when required. This should make the http spans from the api calls of the openai client recorded.
=> elastic-opentelemetry-instrumentation-openai: register import hook for patching

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_with_model_not_found[azure_provider_chat_completions].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_with_model_not_found[ollama_provider_chat_completions].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_with_model_not_found[openai_provider_chat_completions].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_embeddings/test_model_not_found[azure_provider_embeddings].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_embeddings/test_model_not_found[ollama_provider_embeddings].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_embeddings/test_model_not_found[openai_provider_embeddings].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/conftest.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_embeddings.py
And remove the assumptions that expected it to be always present.
=> elastic-opentelemetry-instrumentation-openai: test calls with model not found

instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_exported_schema_version.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/conftest.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_instrumentor.py
Add proper test instead of asserting against mocks.
=> elastic-opentelemetry-instrumentation-openai: assert exported schema version

.github/workflows/ci.yml, instrumentation/elastic-opentelemetry-instrumentation-openai/README.md, instrumentation/elastic-opentelemetry-instrumentation-openai/pyproject.toml, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/package.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/wrappers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/conftest.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_embeddings.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/utils.py
This adds a bunch of integration tests hitting openai. This requires
setting a variable OPENAI_API_KEY in github secrets. Tests themselves
are a copy of the recorded ones asserting values from the response data.
Integration tests are not run by default and can be called with pytest --integration-tests
Then adds unit testing against 1.2.0 baseline. 1.26.0 is required for having usage data with streams but with some
small changes we can keep the baseline as old as 1.2.0.
=> elastic-opentelemetry-instrumentation-openai: add integrations tests and test on baseline

instrumentation/elastic-opentelemetry-instrumentation-openai/dev-requirements-3.9.txt, instrumentation/elastic-opentelemetry-instrumentation-openai/dev-requirements.txt, instrumentation/elastic-opentelemetry-instrumentation-openai/pyproject.toml
Bump to latest sdk that fixes exporting log events with empty body
=> elastic-opentelemetry-instrumentation-openai: bump to latest sdk

instrumentation/elastic-opentelemetry-instrumentation-openai/README.md, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_embeddings.py
Update attributes to match
https://github.com/open-telemetry/semantic-conventions/pull/1603
=> elastic-opentelemetry-instrumentation-openai: match proposed upstream semconv

.pre-commit-config.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/pyproject.toml, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/wrappers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/conftest.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_embeddings.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/utils.py, pyproject.toml
Centralize it and add more checks to match opentelemetry upstream one.
=> Update ruff configuration

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/wrappers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_all_the_client_options[azure_provider_chat_completions].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_stream_all_the_client_options[azure_provider_chat_completions].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_stream_all_the_client_options[ollama_provider_chat_completions].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/.test_chat_completions/test_stream_all_the_client_options[openai_provider_chat_completions].yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py
This adds support for tracing the following attributes:
- GEN_AI_OPENAI_REQUEST_RESPONSE_FORMAT
- GEN_AI_OPENAI_REQUEST_SEED
- GEN_AI_OPENAI_REQUEST_SERVICE_TIER
- GEN_AI_OPENAI_RESPONSE_SERVICE_TIER
`service_tier` parameter has been added in openai 1.35.0 so skipping on old versions and only reported in the response by openai anyway.
=> elastic-opentelemetry-instrumentation-openai: match all the attributes traced upstream

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/wrappers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py
So that it still sends events but clears the message content key.
=> elastic-opentelemetry-instrumentation-openai: make OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT work like upstream

.github/workflows/ci.yml
CI runs from PR done from forks are failing the integrations tests step because the OPENAI_API_KEY secret is not available to them.
=> ci: don't run integrations tests without openai api key

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/wrappers.py
When spans are not recording the attributes are not accessible and so we'll crash trying to access them in metrics code. So decouple the metrics code from the span and instead use the plain attributes.
Closes #53
=> openai: decouple metrics from span recording

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/test_chat_all_the_client_options_not_given.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/test_embeddings_all_the_client_options_not_given.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_embeddings.py
Empty api parameters may just not be None but also `openai.NotGiven` istances, handle the case to avoid setting invalid span attributes
Closes #66
=> openai: don't set attributes if they are NotGiven

instrumentation/elastic-opentelemetry-instrumentation-openai/pyproject.toml, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/test_parse_response_format_json_object_with_capture_message_content.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/test_parse_response_format_structured_output_with_capture_message_content.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_beta_chat_completions.py
Pydantic types are passed directly in as the response_format.
e.g. from DeepSeek:
```python
if self.model_name in structured_outputs_models:
print(f"structured_outputs_models: {type(schema)}")
completion = await client.beta.chat.completions.parse(
model=self.model_name,
messages=[
{"role": "user", "content": prompt},
],
response_format=schema,
)
```
These are lazily resolved with logic we unlikely want to recreate here, so this just maps the default case where we don't have a string to `json_schema`.
In doing so, I can see this removes the attribute warnings below as the value is now always a string:
```
WARNING  opentelemetry.attributes:__init__.py:100 Invalid type ModelMetaclass for attribute 'gen_ai.openai.request.response_format' value. Expected one of ['bool', 'str', 'bytes', 'int', …
```
=> Maps non-string, non-dict schema as json_schema

instrumentation/elastic-opentelemetry-instrumentation-openai/dev-requirements-3.9.txt, instrumentation/elastic-opentelemetry-instrumentation-openai/dev-requirements.txt, instrumentation/elastic-opentelemetry-instrumentation-openai/pyproject.toml, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/metrics.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/conftest.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/utils.py
Update metrics setup code to use the suggested genai buckets for operation duration and token usage.
Closes #49
=> openai: use proper genai suggested buckets for metrics

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/wrappers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/test_chat_stream_with_raw_response.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/test_chat_with_raw_response.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py
This change StreamWrapper to intherit from ObjectProxy so we have whatever attribute the callers expect. Then we need to handle the case when the response of the api call is a LegacyAPIResponse that needs to parsed.
Refs #61
=> openai: fix instrumentation of with_raw_response

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/__init__.py, instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/helpers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_beta_chat_completions.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py
- Use `gen_ai.output.type` instead of deprecated `gen_ai.openai.request.response_format` attribute.
- Use `json` instead of `json_schema|json_object` for `gen_ai.output.type` attribute value, as the enum options for the new attribute changed to be more generic (see [here](https://github.com/open-telemetry/opentelemetry-python/blob/main/opentelemetry-semantic-conventions/src/opentelemetry/semconv/_incubating/attributes/gen_ai_attributes.py#L257))
- Update tests to reflect the changes above.
- Change in the semantic conventions: https://github.com/open-telemetry/semantic-conventions/pull/1757
Closes #52
=> Add semconv-1.31.0 changes to openai instrumentation 

instrumentation/elastic-opentelemetry-instrumentation-openai/src/opentelemetry/instrumentation/openai/wrappers.py, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/cassettes/test_chat_stream_with_context_manager.yaml, instrumentation/elastic-opentelemetry-instrumentation-openai/tests/test_chat_completions.py
- Resolves the issue of missing openai instrumentation surface in our "dogfood" chatbot rag app.
- Solution inspired by amazing deep dive from @xrmx , with some minor additions to resolve the issue for async calls too.
- Update`StreamWrapper` to close the span only once, either when context manager exits or when end of stream is reached
- Same logic is applied for both sync and async
1. After reproducing the issue following these steps, I applied the patch mentioned in the same link.
2. Confirmed the patch resolves the issue
3. Wrote unit tests for chat_stream* methods for cases when context manager is used and confirmed that without a patch these tests fail and issue `WARNING  opentelemetry.sdk.trace:__init__.py:943 Calling end() on an ended span.` 
4. Applied the patch and expanded it …
=> openai: Fix span closure when using context manager

.github/workflows/ci.yml, instrumentation/elastic-opentelemetry-instrumentation-openai/pyproject.toml
Test on Python 3.13 and add it to the package trove classifiers.
=> openai: test on python 3.13
